# This workflow will scrap GitHub trending projects daily.

name: Daily Github Trending

on:
  push:
    branches:
      - main
      - "releases/**"
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"
      - name: 安装依赖
        run: pnpm install
      - name: 开始获取数据
        run: pnpm run dev
      # Runs a set of commands using the runners shell
      - name: 提交数据
        run: |
          echo start push
          git config --global user.name ${{secrets.USERNAME}}
          git config --global user.email ${{secrets.EMAIL}}

          git add -A
          git commit -m $(date '+%Y-%m-%d')
          git push
          echo end push
